### ISSUE TITLE
Need a tutorial for the user

### ISSUE THREAD

**Issue by nylonee** [nylonee/hangupsbot#125]
There needs to be a brief wiki for the user on getting started with the bot, perhaps using `/bot help` and `/bot help <command>` to redirect the user to different wiki pages within hangouts.

Ideally the links to the wiki should be easily configurable, in case an organization wants to replace the links with their own wikis.

**Comment by endofline** [comment]
Start updating it here: https://github.com/nylonee/hangupsbot/wiki/User-Guide

**Comment by endofline** [comment]
implements the basics first, you can now add the `config.json` key `link_to_guide` for an extra line to pop up when users request general help (via `/bot help`) - as long as `config.link_to_guide` is defined, the added line (after the user command list) is: `For more information, please see: <link>`. As an added feature, different help can be displayed for different conversations as it uses `bot.get_config_suboption(conv_id, ...)`

i recommend just creating a single wiki link first and putting a proper TOC there for quick reference by users rather than multiple links

**Comment by endofline** [comment]
merged into staging, issue should be left open until **framework/2.4** branch is ready; and the wiki link above is prepared
