### ISSUE TITLE
bot.memory changes not saved to disk

### ISSUE THREAD

**Issue by kilr00y** [nylonee/hangupsbot#129]
when directly manipulating bot.memory and calling bot.memory.save() changes remain im memory only and are not written to disk when keys need to be overwritten and/or deleted. 

~~workaround:~~

~~set bot.memory.changed = true before calling bot.memory.save()~~ 

Edited by endofline (see below)

**Comment by endofline** [comment]
Use `bot.memory.force_taint()` instead as a more modular way to inform the bot that memory has changed. This situation may arise due to the following scenario:
* using a `del` to delete a root key will not automatically trigger taint - use `bot.memory.pop("<root key>")` instead
* attempting to set a subkey directly e.g. memory.bot["root"]["subkey"] = "xyz" will also not automatically trigger taint - use `bot.memory.set_by_path()` instead ([docs](https://github.com/nylonee/hangupsbot/wiki/%60bot%60-functions-for-developers#settingretrieving-memory-1))

the missing functionality here is the lack of a "remove/delete key" function in config.py

**Comment by endofline** [comment]
will be closed after adding missing functionality to config.py
