### ISSUE TITLE
enh request: convtools_invitations plugin

### ISSUE THREAD

**Issue by FrNico** [nylonee/hangupsbot#167]
After deploying convtools_invitation on few bots, I got some feedback from users, regarding some feature requests:
* [x] issue_invite_on_exit: config parameter to enable/disable globally and per conv (similar to monitorsadds)

* [x] admin command to purge list pending invites / and/or for a specific user and/or for a specific conversation
Example: /invite list [all | user xxxxx | conv xxxx]

* [x] admin command to purge all pending invites / and/or for a specific user and/or for a specific conversation
Example: /bot invite purge [all | user xxxxx | conv xxxx]

* [x] When creating invites to a new conv, allow bot to create that new conversation:
Example: /bot invite to createnew users from xxxx
will create a new conv and will create invites for people in conv_id xxxx.

Even better: allow to set topic for that conversation at the same time:
Example: /bot invite to createnew name Blabla users from xxxx
will create a new conv, set its name to "Blabla" and will create invites for people in conv_id xxxx.

**Comment by nylonee** [comment]
* Added to the config:
```
'disable_invites_on_exit'
```
When set to true, will disable all invites that are created when users exit a chat. Will remain enabled otherwise
* Added `/bot invite list` to list all pending invites
* Added `/bot invite purge` to purge all pending invites
* Changed the design of invite to allow for conversations to be created where needed. It also actually simplifies the invite logic to:

```
/bot invite <wildcard> [to] [from] [users]
'to': If none, create new chat
'from': If none, assume current chat
'users': If none, assume all users in 'from' chat
```

Wiki also updated. This will automatically close when merged into master
