### ISSUE TITLE
URL in autoreplies are in plain text

### ISSUE THREAD

**Issue by prey87** [nylonee/hangupsbot#171]
If i add a URL to autoreplies the bot send it as plain text and noch as clickable url.

**Comment by nylonee** [comment]
To be more specific, the issue appears to only happen on the desktop version of Hangouts. The mobile client appears to have a built-in URL detector that turns them into links.

I will probably apply `send_message_parsed()` so that all URL's that begin with http:// or https:// will be parsed as an HTML href tag instead.

**Comment by nylonee** [comment]
Note: This will also have the added side-effect of treating all autoreply messages as HTML.

So you can now do bold, italics, newlines etc.
