### ISSUE TITLE
After first start got this, and after restart bot do not respond to querry

### ISSUE THREAD

**Issue by sasha2002** [nylonee/hangupsbot#20]
```
# python3 hangupsbot.py -d
memory file will be used
creating memory file: /root/.local/share/hangupsbot/memory.json
Email: USER@gmail.com
Password:

logger failed to initialise: config.hooks[].storage_path cannot be empty
hook failed to initialise
hook inited: ['hooks', 'hubotsend', 'post', 'sender']
1 hook(s) loaded
config.jsonrpc[0].certfile must be configured
config.jsonrpc[1].certfile must be configured
config.jsonrpc[2].certfile must be configured
thread starting: ['sinks', 'hubotreceive', 'post', 'receiver']
setting event loop
1 sink thread(s) started
setting static reference to bot
pem file possibly missing or broken (== '/root/server.pem')
Connected!
```

**Comment by nylonee** [comment]
Several things happening here.
Let's look at the error messages first:
```
logger failed to initialise: config.hooks[].storage_path cannot be empty
...
config.jsonrpc[0].certfile must be configured
```
While the bot works straight out of the box, it by default attempts to connect to the hooks and sinks specified in the config.json. All of these error message are the bot trying to connect to hooks and sinks that are not configured yet. You can choose to configure them by going to ~/.local/share/hangupsbot/config.json and editing the specific sinks and hooks, or remove them completely from that file to have them not load on startup.

`pem file possibly missing or broken (== '/root/server.pem')`  
This issue is also related to unconfigured hooks/sinks, but if you would like to set up a pem file (it's good practice for future hooks/sinks that you'd like to connect), [this](https://github.com/nylonee/hangupsbot#gitlab-users-web-hook-sinkreceiver) should be able to help

"After restart bot does not respond to queries"
I believe that this problem may lie not within the hangupsbot library, but the main hangups library. I've requested a [pull request](https://github.com/tdryer/hangups/pull/57) as of writing this, and TDryer has referenced the issue [here](https://github.com/tdryer/hangups/issues/58), including a workaround. It's related to a race condition that appears to affect some users and not others.

**Comment by sasha2002** [comment]
@nylonee Thanks for reply, now is start and work.
Another things that i can't use Russian words(not try another one like Chinese) in parsing reply. I mean in "autoreplies" in the first word like "hi bot".

**Comment by nylonee** [comment]
Hmm. That's likely due to the config not being parsed in in the right encoding. I will mark this as a bug and see what I can do about changing the character encoding to UTF-8.
Thanks @sasha2002
