### ISSUE TITLE
subscribe-omnibus-enhancements

### ISSUE THREAD

**Issue by endofline** [nylonee/hangupsbot#34]
1. do not notify users if they mention their own subscribed keyword
    * when subscribing, users should be informed of this so they don't self-test
2. do not send any notifications when in 1on1 conversations
3. lowercase/uppercase the subscribed word to ignore casing altogether instead 
  of per-iteration `.lower()` 
4. suggestion: alternate type of whole-word matching? python supports word boundaries:
```
x = "b"
y = "a b c"
x = "\\b" + x + "\\b"
re.search(x, y, re.IGNORECASE)
```

**Comment by nylonee** [comment]
1. Fixed in commit https://github.com/nylonee/hangupsbot/commit/e78c5a94f01f9afdc9846edbd592c2fda32f2438
1a. Fixed in commit https://github.com/nylonee/hangupsbot/commit/b56085c4ea66bd1333de44fb4860442251c3bb2c
2. Automatically resolved by first commit
3. Fixed in commit https://github.com/nylonee/hangupsbot/commit/863ec5544eb71d413eb048958672c27cb6c2b719
4. Fixed in commit https://github.com/nylonee/hangupsbot/commit/90e08511cdb5f3c82b2fd9a256c3763f25b260f5
