### ISSUE TITLE
[feature] auto-translation of forwarded/sync hangouts

### ISSUE THREAD

**Issue by endofline** [nylonee/hangupsbot#73]
for some unknown reason, this scares me... preliminary roadmap:
* [x] store "native" 2-letter iso language code in conversation memory
* [x] modify sending handler to allow in-line translation of outgoing messages
* [x] implement support for automatic translation between forwarded/synced hangouts

this list is subject to change

**Comment by j16sdiz** [comment]
Some suggestions:

1. Change `context` in `send_message_segments` to a list of flags. Allowing other plugins to optionally skip syncout / autostranslate for their message.

2. Instead of changing code syncout, make `register_handler(func, type='sending')` do a filter chains. The `autotranslate` can then add a filter to sending filter chain. This avoid some inter-dependency between syncout and autotranslate.

**Comment by endofline** [comment]
will be implementing a preliminary translator at the `syncout:_handle_incoming_message()` code first, prior to doing crazy stuff at the `sending` handler - you're right though @j16sdiz: the `context` parameter can contain much more than what it is being used for presently even in the original syncout plugins, and having a more customisable chain at the sending level was the original intent.

**Comment by endofline** [comment]
The usage of `context` has been expanded - autotranslation now only kicks in automatically for non- `/bot` and `/me` messages which are explicitly relayed by the syncrooms plugin. Other plugins won't be affected by the translation service for now, unless you specifically program them in to add the autotranslate `context` as follows:
```
context["autotranslate"] = {
    "conv_id" : <the originating event id, needed to find origin language>,
    "event_text" : <plaintext of the message> 
}
```

**Comment by nylonee** [comment]
Closing this (Since it didn't auto-close with #74 merge)
